export const ADMIN_PRODUCT_ACTION_TYPES = {
  FETCH_ADMIN_PRODUCT_START: "adminProduct/FETCH_ADMIN_PRODUCT_START",
  FETCH_ADMIN_PRODUCT_SUCCESS: "adminProduct/FETCH_ADMIN_PRODUCT_SUCCESS",
  FETCH_ADMIN_PRODUCT_FAILED: "adminProduct/FETCH_ADMIN_PRODUCT_FAILED",
  DELETE_ADMIN_PRODUCT_START: "adminProduct/DELETE_ADMIN_PRODUCT_START",
  DELETE_ADMIN_PRODUCT_SUCCESS: "adminProduct/DELETE_ADMIN_PRODUCT_SUCCESS",
  DELETE_ADMIN_PRODUCT_FAILED: "adminProduct/DELETE_ADMIN_PRODUCT_FAILED",
  SET_ADMIN_PRODUCT_IS_OPEN: "adminProduct/SET_ADMIN_PRODUCT_IS_OPEN",
};
