export const ADMIN_PRODUCT_ACTION_TYPES = {
  FETCH_ADMIN_PRODUCT_START: "adminProduct/FETCH_ADMIN_PRODUCT_START",
  FETCH_ADMIN_PRODUCT_SUCCESS: "adminProduct/FETCH_ADMIN_PRODUCT_SUCCESS",
  FETCH_ADMIN_PRODUCT_FAILED: "adminProduct/FETCH_ADMIN_PRODUCT_FAILED",
  SET_ADMIN_PRODUCT_START: "adminProduct/SET_ADMIN_PRODUCT_START",
  SET_ADMIN_PRODUCT_SUCCESS: "adminProduct/SET_ADMIN_PRODUCT_SUCCESS",
  SET_ADMIN_PRODUCT_FAILED: "adminProduct/SET_ADMIN_PRODUCT_FAILED",
  SET_ADMIN_PRODUCT_IS_OPEN: "adminProduct/SET_ADMIN_PRODUCT_IS_OPEN",
  SET_ADMIN_PRODUCT_TEMP_DATA: "adminProduct/SET_ADMIN_PRODUCT_TEMP_DATA",
};
