export const ADMIN_ORDERS_ACTION_TYPES = {
  FETCH_ADMIN_ORDERS_START: "adminOrders/FETCH_ADMIN_ORDERS_START",
  FETCH_ADMIN_ORDERS_SUCCESS: "adminOrders/FETCH_ADMIN_ORDERS_SUCCESS",
  FETCH_ADMIN_ORDERS_FAILED: "adminOrders/FETCH_ADMIN_ORDERS_FAILED",
  SET_ADMIN_ORDERS_START: "adminOrders/SET_ADMIN_ORDERS_START",
  SET_ADMIN_ORDERS_SUCCESS: "adminOrders/SET_ADMIN_ORDERS_SUCCESS",
  SET_ADMIN_ORDERS_FAILED: "adminOrders/SET_ADMIN_ORDERS_FAILED",
  SET_ADMIN_ORDERS_MODAL_OPEN: "adminOrders/SET_ADMIN_ORDERS_MODAL_OPEN",
  SET_ADMIN_ORDERS_TEMP_DATA: "adminOrders/SET_ADMIN_ORDERS_TEMP_DATA",
};
