export const ADMIN_ORDERS_ACTION_TYPES = {
  FETCH_ADMIN_ORDERS_START: "adminOrders/FETCH_ADMIN_ORDERS_START",
  FETCH_ADMIN_ORDERS_SUCCESS: "adminOrders/FETCH_ADMIN_ORDERS_SUCCESS",
  FETCH_ADMIN_ORDERS_FAILED: "adminOrders/FETCH_ADMIN_ORDERS_FAILED",
};
