export const USER_PRODUCT_ACTION_TYPES = {
  FETCH_USER_PRODUCT_START: "userProducts/FETCH_USER_PRODUCT_START",
  FETCH_USER_PRODUCT_SUCCESS: "userProducts/FETCH_USER_PRODUCT_SUCCESS",
  FETCH_USER_PRODUCT_FAILED: "userProducts/FETCH_USER_PRODUCT_FAILED",
  FETCH_USER_SINGLE_PRODUCT_START:
    "userProducts/FETCH_USER_SINGLE_PRODUCT_START",
  FETCH_USER_SINGLE_PRODUCT_SUCCESS:
    "userProducts/FETCH_USER_SINGLE_PRODUCT_SUCCESS",
  FETCH_USER_SINGLE_PRODUCT_FAILED:
    "userProducts/FETCH_USER_SINGLE_PRODUCT_FAILED",
  CLEAR_USER_PRODUCT: "userProducts/CLEAR_USER_PRODUCT",
};
