export const USER_PRODUCT_ACTION_TYPES = {
  FETCH_USER_PRODUCT_START: "userProduct/FETCH_USER_PRODUCT_START",
  FETCH_USER_PRODUCT_SUCCESS: "userProduct/FETCH_USER_PRODUCT_SUCCESS",
  FETCH_USER_PRODUCT_FAILED: "userProduct/FETCH_USER_PRODUCT_FAILED",
  FETCH_USER_SINGLE_PRODUCT_START:
    "userProduct/FETCH_USER_SINGLE_PRODUCT_START",
  FETCH_USER_SINGLE_PRODUCT_SUCCESS:
    "userProduct/FETCH_USER_SINGLE_PRODUCT_SUCCESS",
  FETCH_USER_SINGLE_PRODUCT_FAILED:
    "userProduct/FETCH_USER_SINGLE_PRODUCT_FAILED",
};
