export const USER_ACTION_TYPES = {
  LOG_IN_START: "user/LOG_IN_START",
  LOG_IN_SUCCESS: "user/LOG_IN_SUCCESS",
  LOG_IN_FAILED: "user/LOG_IN_FAILED",
  SET_USER_FAVORITE: "user/SET_USER_FAVORITE",
};
