export const ADMIN_COUPONS_ACTION_TYPES = {
  FETCH_ADMIN_COUPONS_START: "adminCoupons/FETCH_ADMIN_COUPONS_START",
  FETCH_ADMIN_COUPONS_SUCCESS: "adminCoupons/FETCH_ADMIN_COUPONS_SUCCESS",
  FETCH_ADMIN_COUPONS_FAILED: "adminCoupons/FETCH_ADMIN_COUPONS_FAILED",
};
