export const ADMIN_COUPONS_ACTION_TYPES = {
  FETCH_ADMIN_COUPONS_START: "adminCoupons/FETCH_ADMIN_COUPONS_START",
  FETCH_ADMIN_COUPONS_SUCCESS: "adminCoupons/FETCH_ADMIN_COUPONS_SUCCESS",
  FETCH_ADMIN_COUPONS_FAILED: "adminCoupons/FETCH_ADMIN_COUPONS_FAILED",
  SET_ADMIN_COUPONS_START: "adminCoupons/SET_ADMIN_COUPONS_START",
  SET_ADMIN_COUPONS_SUCCESS: "adminCoupons/SET_ADMIN_COUPONS_SUCCESS",
  SET_ADMIN_COUPONS_FAILED: "adminCoupons/SET_ADMIN_COUPONS_FAILED",
  SET_ADMIN_COUPONS_IS_OPEN: "adminCoupons/SET_ADMIN_COUPONS_IS_OPEN",
  SET_ADMIN_COUPONS_TEMP_DATA: "adminCoupons/SET_ADMIN_COUPONS_TEMP_DATA",
};
