export const ADMIN_COUPONS_ACTION_TYPES = {
  FETCH_ADMIN_COUPONS_START: "adminCoupons/FETCH_ADMIN_COUPONS_START",
  FETCH_ADMIN_COUPONS_SUCCESS: "adminCoupons/FETCH_ADMIN_COUPONS_SUCCESS",
  FETCH_ADMIN_COUPONS_FAILED: "adminCoupons/FETCH_ADMIN_COUPONS_FAILED",
  DELETE_ADMIN_COUPONS_START: "adminCoupons/DELETE_ADMIN_COUPONS_START",
  DELETE_ADMIN_COUPONS_SUCCESS: "adminCoupons/DELETE_ADMIN_COUPONS_SUCCESS",
  DELETE_ADMIN_COUPONS_FAILED: "adminCoupons/DELETE_ADMIN_COUPONS_FAILED",
  SET_ADMIN_COUPONS_IS_OPEN: "adminCoupons/SET_ADMIN_COUPONS_IS_OPEN",
};
