export const USER_ORDER_ACTION_TYPES = {
  SET_USER_ORDER_START: "userOrder/SET_USER_ORDER_START",
  SET_USER_ORDER_SUCCESS: "userOrder/SET_USER_ORDER_SUCCESS",
  SET_USER_ORDER_FAILED: "userOrder/SET_USER_ORDER_FAILED",
  FETCH_USER_ORDER_DATA_START: "userOrder/FETCH_USER_ORDER_DATA_START",
  FETCH_USER_ORDER_DATA_SUCCESS: "userOrder/FETCH_USER_ORDER_DATA_SUCCESS",
  FETCH_USER_ORDER_DATA_FAILED: "userOrder/FETCH_USER_ORDER_DATA_FAILED",
  SET_CLEAR_USER_ORDER_STATE: "userOrder/SET_CLEAR_USER_ORDER_STATE",
};
