export const USER_ORDER_ACTION_TYPES = {
  SET_USER_ORDER_START: "userOrder/SET_USER_ORDER_START",
  SET_USER_ORDER_SUCCESS: "userOrder/SET_USER_ORDER_SUCCESS",
  SET_USER_ORDER_FAILED: "userOrder/SET_USER_ORDER_FAILED",
};
