export const CART_ACTION_TYPES = {
  FETCH_CART_ITEMS_START: "cart/FETCH_CART_ITEMS_START",
  FETCH_CART_ITEMS_SUCCESS: "cart/FETCH_CART_ITEMS_SUCCESS",
  FETCH_CART_ITEMS_FAILED: "cart/FETCH_CART_ITEMS_FAILED",
  ADD_CART_ITEMS_START: "cart/ADD_CART_ITEMS_START",
  ADD_CART_ITEMS_SUCCESS: "cart/ADD_CART_ITEMS_SUCCESS",
  ADD_CART_ITEMS_FAILED: "cart/ADD_CART_ITEMS_FAILED",
};
