export const CART_ACTION_TYPES = {
  FETCH_CART_ITEMS_START: "cart/FETCH_CART_ITEMS_START",
  FETCH_CART_ITEMS_SUCCESS: "cart/FETCH_CART_ITEMS_SUCCESS",
  FETCH_CART_ITEMS_FAILED: "cart/FETCH_CART_ITEMS_FAILED",
  SET_CART_ITEMS_START: "cart/SET_CART_ITEMS_START",
  SET_CART_ITEMS_SUCCESS: "cart/SET_CART_ITEMS_SUCCESS",
  SET_CART_ITEMS_FAILED: "cart/SET_CART_ITEMS_UPDATE_FAILED",
  SET_CART_ITEMS_UPDATE_START: "cart/SET_CART_ITEMS_UPDATE_START",
  SET_CART_ITEMS_UPDATE_SUCCESS: "cart/SET_CART_ITEMS_UPDATE_SUCCESS",
  SET_CART_ITEMS_UPDATE_FAILED: "cart/SET_CART_ITEMS_UPDATE_FAILED",
};
